### ISSUE TITLE
fails when BPM isn't detected

### ISSUE THREAD

**Issue by yocontra** [sakemin/cog-musicgen-remixer#2]
https://replicate.com/p/s2fuxkdblz75o7mdrviv6gtn6q

```
Analyzing tmpwhp79aorflower-duet-cropped.mp3: 100%|██████████| 1/1 [00:00<00:00,  5.55it/s]
BPM :  None
Traceback (most recent call last):
File "/root/.pyenv/versions/3.9.18/lib/python3.9/site-packages/cog/server/worker.py", line 217, in _predict
result = predict(**payload)
File "predict.py", line 258, in predict
prompt = prompt + f', bpm : {int(music_input_analysis.bpm)}'
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

If the BPM fails to be detected it should probably just omit the `bpm:` input to the model so you can still get some output. Optionally I think the BPM/downbeat detection could be improved - I've seen issues on most songs I've tested with where it incorrectly identifies beat changes where there are none.

**Comment by sakemin** [comment]
Hello @yocontra !
Does the input audio not have a distinguishable beats?
It's the first time failing to retrieve bpm. I'll work on a patch with `bpm==None` case.
Thanks for reporting!

**Comment by yocontra** [comment]
@sakemin I would guess the actual BPM is ~4 in this sample audio, if you check the replicate.com link you can listen to the audio I used (flower duet, classical song - has some soft slow strings in the background during this section)

**Comment by sakemin** [comment]
@yocontra 
I just pushed a new model! Can you try again with version `70fa9383`?
Also pushed on github repo. https://github.com/sakemin/cog-musicgen-remixer/commit/6179c8c2cb3252dd305484ea81c2596b5b13ef88

**Comment by sakemin** [comment]
https://github.com/sakemin/cog-musicgen-remixer/commit/6179c8c2cb3252dd305484ea81c2596b5b13ef88

**Comment by sakemin** [comment]
https://replicate.com/p/fjlbjj3bf475omhejhuwebgjr4

It also fails to retrieve downbeats.
Adding another case right now!

**Comment by sakemin** [comment]
@yocontra 
Versions (e7172deb) is working with your prediction!
https://replicate.com/p/ahucrbdbsptbrheo5ppbmslsja
