### ISSUE TITLE
Replicate musicgen remixer not working

### ISSUE THREAD

**Issue by Kentwwx** [sakemin/cog-musicgen-remixer#3]

**Comment by Kentwwx** [comment]
It's a very good model. Previously we could use this model on replicate, but now it is disabled. May I ask if could you help fix it on Replicate? It would be extremely helpful. Thanks!

**Comment by sakemin** [comment]
Hello @Kentwwx ,
Thanks for reporting the model is disabled.
Since there was an update on the system of Replicate and Cog, some of the model crashed while booting and got automatically disabled.
Now it is fixed, and you can use it again!
Thanks for enjoying my model :)
