### ISSUE TITLE
Silent File Generated

### ISSUE THREAD

**Issue by apiss2** [sakemin/cog-musicgen-remixer#5]
I ran docker on Windows as follows:

```bash
docker run -v musicgen-remixer:/src/ --gpus all r8.im/sakemin/musicgen-remixer@sha256:0b769f28e399c7c30e4f2360691b9b11c294183e9ab2fd9f3398127b556c86d7
```

After starting a local server with Python, I used curl to send a request to the docker server as shown below:

```bash
curl -o output.json -X POST -H "Content-Type: application/json" -d $'{"input": {"prompt": "progressive house","music_input": "http://host.docker.internal:8000/my_music_file.mp3","output_format": "wav"}}' http://localhost:5000/predictions
```

When running the above command, a silent file is generated. While it works fine when using the sample music provided in the tutorial.

For example, specifying the following URL for "music_input" results in successful generation: [Sample Music URL](https://replicate.delivery/pbxt/Jo5eWjg3NvEVtAowTbAOAUiyplQjUA4Sfn0QkOhm8FdQEmv5/Ditto-2-NewJeans.mp3)

What file format is recommended for input files?

**Comment by sakemin** [comment]
Hello,

mp3 and wav format are compatible for this.
Is the header of the audio file not corrupted?

**Comment by apiss2** [comment]
Thank you for your reply.

As advised, it seems that a certain tag was the cause of the issue.
I tried various things, and when I removed all the tags, it worked fine!
